### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [Devistallion/prj-rev-bwfs-dasmoto#4]
Summary met expectations.

So in this first project I really focus on two items. 

First did you use divs to organized sections of your content.
Your html is well structured and is exactly what I am looking for in this exercise.  

FYI I don't see the b element used anymore, that is because the html 5 spec tells you to avoid it unless absolutely necessary.  This is why I mentioned span.

> The b element should be used as a last resort when no other element is more appropriate. In particular, headings should use the h1 to h6 elements, stress emphasis should use the em element, importance should be denoted with the strong element, and text marked or highlighted should use the mark element.

https://www.w3.org/TR/html5/text-level-semantics.html#the-b-element

The second thing I look for is repetition in css.  We want to be as efficient as possible.  The reason being is the less you type the less likely you are going to make a mistake.

Except for font-family your css is well structured and had everything else I look for in this project.
The mistake usually happens in this first project so I wouldn't worried about it now that you are aware of it.

To prepare you for the upcoming projects and as a challenge go to flexboxfroggy.com.  See how far you can get as the future projects will be using flexbox heavily.

**Comment by Devistallion** [comment]
Thank you for pointing out the b element. I learned html a long time ago, and had not encountered strong, so I had asked why one had replaced the other, but didn't quite get a clear answer. That particular section threw me for a moment.

I followed the instructions exactly mostly because I wasn't sure if there would be certain sections the reviewers were looking for, such as the css being exactly as asked in the Spec. Now that I know it's about efficiency, I'll try to make my code more streamlined. As for spelling, I even made myself an extra note, but one still got away.

Thank you for the review.
